# Problem Statement:
=>Predict the percentage of marks obtained by the student based on the number of hours studeied by the student.             

=>Evaluate the model.

=>Use Regression=Method

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

# Load the dataset

In [2]:
url=('http://bit.ly/w-data')
df=pd.read_csv(url)

In [3]:
df.shape

(25, 2)

In [4]:
df.head(10)

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30
5    1.5      20
6    9.2      88
7    5.5      60
8    8.3      81
9    2.7      25

# Independent and Dependent Variables:

In [5]:
#Independent Variable
X=df['Hours']
#Dependent Variables
y=df['Scores']

In [6]:
X=X.values.reshape(25,1)

In [7]:
y=y.values.reshape(25,1)

# Model:

In [8]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [9]:
reg.fit(X,y)

LinearRegression()

# R-Squared:

In [10]:
reg.score(X,y)

0.9529481969048356

# Coefficient:

In [11]:
reg.coef_

array([[9.77580339]])

# Intercept:

In [12]:
reg.intercept_

array([2.48367341])

# Prediction:

In [13]:
new=pd.DataFrame(data=[1.8,5.1,2.7],columns=['Hours'])
new

Hours
0    1.8
1    5.1
2    2.7

In [14]:
s1=reg.predict(new)
s1

array([[20.08011951],
       [52.3402707 ],
       [28.87834256]])

In [15]:
predicted=pd.DataFrame(s1,columns=['Scores'])
predicted

Scores
0  20.080120
1  52.340271
2  28.878343

In [16]:
new.join(predicted)

Hours     Scores
0    1.8  20.080120
1    5.1  52.340271
2    2.7  28.878343

In [17]:
df1=pd.DataFrame(df['Hours'],columns=['Hours'])
df1

Hours
0     2.5
1     5.1
2     3.2
3     8.5
4     3.5
5     1.5
6     9.2
7     5.5
8     8.3
9     2.7
10    7.7
11    5.9
12    4.5
13    3.3
14    1.1
15    8.9
16    2.5
17    1.9
18    6.1
19    7.4
20    2.7
21    4.8
22    3.8
23    6.9
24    7.8

In [18]:
predicted1=reg.predict(df1)

In [19]:
predicted1=pd.DataFrame(predicted1,columns=['Score'])
predicted1

Score
0   26.923182
1   52.340271
2   33.766244
3   85.578002
4   36.698985
5   17.147378
6   92.421065
7   56.250592
8   83.622842
9   28.878343
10  77.757360
11  60.160913
12  46.474789
13  34.743825
14  13.237057
15  89.488324
16  26.923182
17  21.057700
18  62.116074
19  74.824618
20  28.878343
21  49.407530
22  39.631726
23  69.936717
24  78.734940

In [20]:
df.join(predicted1)

Hours  Scores      Score
0     2.5      21  26.923182
1     5.1      47  52.340271
2     3.2      27  33.766244
3     8.5      75  85.578002
4     3.5      30  36.698985
5     1.5      20  17.147378
6     9.2      88  92.421065
7     5.5      60  56.250592
8     8.3      81  83.622842
9     2.7      25  28.878343
10    7.7      85  77.757360
11    5.9      62  60.160913
12    4.5      41  46.474789
13    3.3      42  34.743825
14    1.1      17  13.237057
15    8.9      95  89.488324
16    2.5      30  26.923182
17    1.9      24  21.057700
18    6.1      67  62.116074
19    7.4      69  74.824618
20    2.7      30  28.878343
21    4.8      54  49.407530
22    3.8      35  39.631726
23    6.9      76  69.936717
24    7.8      86  78.734940

# Model-Deployment:

In [21]:
import warnings
warnings.filterwarnings('ignore')

In [22]:
import gradio as gr

def Marks(Hours):
    predictions2=reg.predict(Hours)
    return predictions2

iface = gr.Interface(Marks, 
    gr.inputs.Dataframe(
        headers=["Hours"],
        #default=[["Jon", 12, 14, 18], ["Alice", 14, 17, 2], ["Sana", 8, 9.5, 12]]
    ),
    [
        "dataframe"
        
    ],
    description="Please enter the number of hours you studied:"
)
iface.launch()

Running locally at: http://127.0.0.1:7860/
To create a public link, set `share=True` in `launch()`.
Interface loading below...


(<Flask 'gradio.networking'>, 'http://127.0.0.1:7860/', None)